export declare const icons: {
    account: string;
    doc: string;
    vk: string;
    youtube: string;
    video: string;
    yandex: string;
    menu: string;
    close: string;
    'arrow-down': string;
    car: string;
    review: string;
    phone: string;
    circle: string;
    dzen: string;
    instagram: string;
    moon: string;
    sun: string;
    edit: string;
    visibility: string;
    visibility_off: string;
};
export type TIcon = keyof typeof icons;
